In [1]:
import numpy as np

In [2]:
marks = [
    [99, 90, 89],
    [100, 78, 80],
    [88, 99, 100]
]

In [7]:
n1 = np.array(marks, dtype=np.int16)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

[[ 99  90  89]
 [100  78  80]
 [ 88  99 100]]
<class 'numpy.ndarray'>
2
(3, 3)
int16


In [16]:
# indexing
print(n1)
print(n1[-1])
print(n1[0])
print(n1[[0, -1]])

print(n1[-1][1]) # done in python 2 dimensional lists
print(n1[-1, 1]) # faster and numpy way
print(n1[1, -1])

[[ 99  90  89]
 [100  78  80]
 [ 88  99 100]]
[ 88  99 100]
[99 90 89]
[[ 99  90  89]
 [ 88  99 100]]
99
99
80


In [21]:
# slicing
print(n1)
print(n1[:2])

# chemistry and maths marks scored by the first 2 students of the class
print(n1[:2, 1:])

# physics and chemistry marks scored by the last 2 students od the class
print(n1[-2:, :2])

[[ 99  90  89]
 [100  78  80]
 [ 88  99 100]]
[[ 99  90  89]
 [100  78  80]]
[[90 89]
 [78 80]]
[[100  78]
 [ 88  99]]


In [24]:
# indexing + slicing
print(n1)

# chemistry and maths marks scored by the first and last student of the class
print(n1[[0, -1], 1:])

# physics and maths marks scored by the first 2 students of the class
print(n1[:2, [0, -1]])

[[ 99  90  89]
 [100  78  80]
 [ 88  99 100]]
[[ 90  89]
 [ 99 100]]
[[ 99  89]
 [100  80]]


In [28]:
# descriptive statistics
print(n1)
print(n1.mean(axis=0)) # vertical
print(n1.sum(axis=1)) # horizontal

[[ 99  90  89]
 [100  78  80]
 [ 88  99 100]]
[95.66666667 89.         89.66666667]
[278 258 287]
