In [1]:
import numpy as np

In [4]:
print(np.ones(10))
print(np.zeros(20))
print(np.arange(5, 18))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17]


In [7]:
print(np.identity(3))
print(np.arange(1, 10).reshape(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
