In [37]:
import numpy as np

In [38]:
marks = [5, 6, 10, 6, 7, 3, 4, 10, 10, 1]

In [39]:
# visualize data as a numpy ndarray
n1 = np.array(marks, dtype=np.int8)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

[ 5  6 10  6  7  3  4 10 10  1]
<class 'numpy.ndarray'>
1
(10,)
int8


In [40]:
# Vectorized arithmetic operations
# Deduct 1 mark from every student of the class
n2 = n1 - 1
print(n2)

n3 = n2 + 1
print(n3)

[4 5 9 5 6 2 3 9 9 0]
[ 5  6 10  6  7  3  4 10 10  1]


In [41]:
# indexing in a numpy ndarray
print(n1[0])
print(n1[-2])
print(n1[[0, -1]]) # multi indexing

# modify the marks scored by the second student of the class
n1[1] = 8
print(n1)
n1[[2, -1]] = 0
print(n1)

5
10
[5 1]
[ 5  8 10  6  7  3  4 10 10  1]
[ 5  8  0  6  7  3  4 10 10  0]


In [43]:
# slicing
print(n1)
first_three = n1[0:3]
print(first_three)
print(n1[:3])
print(n1[-4:])

# slice and modify
''' first_three = n1[:3]
print(first_three)
first_three[0] = 0
print(first_three)
print(n1) '''
n1[:3] = 0
print(n1)

n1[:3] = [1, 3, 5]
print(n1)

[ 0  0  0  6  7  3  4 10 10  0]
[0 0 0]
[0 0 0]
[ 4 10 10  0]
[ 0  0  0  6  7  3  4 10 10  0]
[ 1  3  5  6  7  3  4 10 10  0]


In [52]:
# descriptive statistics
print(n1)
print(n1.mean())
print(np.median(n1))
print(n1.std())
print(n1.var())
print(n1.min())
print(n1.max())

[ 1  3  5  6  7  3  4 10 10  0]
4.9
4.5
3.23882694814033
10.490000000000002
0
10


In [59]:
# filtering
print(n1)
# filter out all the students who got more than 5 marks
print(n1 > 5)
more_than_5 = n1[n1 > 5]
print(more_than_5)

# filter out all the students who either got a 0 or scored 10
n5 = n1[(n1 == 0) | (n1 == 10)] # dont use 'and'. USe '&'
print(n5)

[ 1  3  5  6  7  3  4 10 10  0]
[False False False  True  True False False  True  True False]
[ 6  7 10 10]
[10 10  0]


In [61]:
print(n1)
n6 = np.where(n1 >= 5, 1, 0)
print(n6)

[ 1  3  5  6  7  3  4 10 10  0]
[0 0 1 1 1 0 0 1 1 0]
